### ISSUE TITLE
Down arrow on landing page is not in the center of the circle

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/chea3web#21]
![arrow](https://user-images.githubusercontent.com/12749033/50379235-52369e80-0612-11e9-852b-ccd3c8ce72db.png)

Also, the arrow tail is not connected to the arrowhead which looks weird...

**Comment by alexandrabk** [comment]
Removed this because it was no longer really serving a purpose and adds to clutter. User can navigate via navigation bar.
