### ISSUE TITLE
Highlighted items on networks do not reset

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/chea3web#31]

**Comment by alexandrabk** [comment]
Highlighted nodes on the network do reset (i.e. return to original state) when the user selects "New Query." Is this not what you mean?

**Comment by AviMaayan** [comment]
The highlighted nodes should reflect the expanded table you are currently looking at... So you should have only one table open at a time... So if a person click on another table, the other one that is open should be closed...

**Comment by alexandrabk** [comment]
Got it-- the highlighted nodes will reflect all nodes the user highlights on any currently expanded tables and will reset for any table that is collapsed.
